export const tableNames = {
  USERS: "users",
  CATEGORIES: "categories",
  SUBCATEGORIES: "sub_categories",
  CHILDCATEGORIES: "child_categories",
  BRANDS: "brands",
  PRODUCTS: "products",
  COLLECTIONS: "collections",
  CART: "cart",
  WISHLIST: "wishlist",
  ORDERS: "orders",
  MANAGEWEBSITE: {
    BANNER: "banner",
    SPOTLIGHT: "spot_light",
    CUSTOMERSERVICE: "customer_service",
    DISCOUNTBANNER: "discount_banner",
    FASHIONPRODUCTS: "fashion_products",
    POPULARPRODUCTS: "popular_products",
    CATEGORIES: "categories",
  },
};
